// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7zVfk1ynzIHrpmfWUX1FUbww067Dv7r0',
    appId: '1:355208938257:web:2ad9b4e1301b86f74482b0',
    messagingSenderId: '355208938257',
    projectId: 'harpyapp-29110',
    authDomain: 'harpyapp-29110.firebaseapp.com',
    storageBucket: 'harpyapp-29110.appspot.com',
    measurementId: 'G-B72WF82YVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD01_sTCsMO_j3r5DQ8rC4w2jw7YB9sNAs',
    appId: '1:355208938257:android:8b9b8efc78acd4764482b0',
    messagingSenderId: '355208938257',
    projectId: 'harpyapp-29110',
    storageBucket: 'harpyapp-29110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn0I0F4ywyozxuYprqV_O12H0j8_tbkUY',
    appId: '1:355208938257:ios:bd278322528cfe004482b0',
    messagingSenderId: '355208938257',
    projectId: 'harpyapp-29110',
    storageBucket: 'harpyapp-29110.appspot.com',
    iosClientId: '355208938257-3ioouvaj341chgkf8n114hc4nqiiqj50.apps.googleusercontent.com',
    iosBundleId: 'com.example.harpyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn0I0F4ywyozxuYprqV_O12H0j8_tbkUY',
    appId: '1:355208938257:ios:bd278322528cfe004482b0',
    messagingSenderId: '355208938257',
    projectId: 'harpyapp-29110',
    storageBucket: 'harpyapp-29110.appspot.com',
    iosClientId: '355208938257-3ioouvaj341chgkf8n114hc4nqiiqj50.apps.googleusercontent.com',
    iosBundleId: 'com.example.harpyapp',
  );
}
